"""initial_schema

Revision ID: 2514856685d9
Revises: 
Create Date: 2026-05-26 20:04:00.211211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2514856685d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('inn', name=op.f('uq_companies_inn'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('ozon_accounts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('perf_client_id_encrypted', sa.Text(), nullable=True),
    sa.Column('perf_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ozon_accounts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ozon_accounts'))
    )
    op.create_index(op.f('ix_ozon_accounts_company_id'), 'ozon_accounts', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('payload_before', sa.JSON(), nullable=True),
    sa.Column('payload_after', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('posting_number', sa.String(length=100), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('substatus', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cluster_from', sa.String(length=100), nullable=True),
    sa.Column('cluster_to', sa.String(length=100), nullable=True),
    sa.Column('delivery_method_name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_process_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivering_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_orders_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('ozon_account_id', 'posting_number', name='uq_orders_account_posting')
    )
    op.create_index('ix_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_ozon_account_id'), 'orders', ['ozon_account_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('ozon_sku', sa.BigInteger(), nullable=False),
    sa.Column('ozon_product_id', sa.BigInteger(), nullable=True),
    sa.Column('offer_id', sa.String(length=255), nullable=False),
    sa.Column('fbo_sku', sa.BigInteger(), nullable=True),
    sa.Column('fbs_sku', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('marketing_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_index', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_products_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('ozon_account_id', 'ozon_sku', name='uq_products_account_sku')
    )
    op.create_index('ix_products_offer_id', 'products', ['offer_id'], unique=False)
    op.create_index(op.f('ix_products_ozon_account_id'), 'products', ['ozon_account_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_sync_logs_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_logs'))
    )
    op.create_index(op.f('ix_sync_logs_ozon_account_id'), 'sync_logs', ['ozon_account_id'], unique=False)
    op.create_table('transactions',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ozon_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('operation_type_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accruals', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posting_number', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_transactions_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'ozon_transaction_id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_account_time', 'transactions', ['ozon_account_id', 'time'], unique=False)
    op.create_index('ix_transactions_type', 'transactions', ['operation_type'], unique=False)
    op.create_table('analytics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('hits_view_search', sa.Integer(), nullable=False),
    sa.Column('hits_view_pdp', sa.Integer(), nullable=False),
    sa.Column('hits_tocart_search', sa.Integer(), nullable=False),
    sa.Column('hits_tocart_pdp', sa.Integer(), nullable=False),
    sa.Column('session_view_search', sa.Integer(), nullable=False),
    sa.Column('session_view_pdp', sa.Integer(), nullable=False),
    sa.Column('conv_tocart_search', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('conv_tocart_pdp', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ordered_units', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivered_units', sa.Integer(), nullable=False),
    sa.Column('returns', sa.Integer(), nullable=False),
    sa.Column('cancellations', sa.Integer(), nullable=False),
    sa.Column('adv_view_pdp', sa.Integer(), nullable=False),
    sa.Column('adv_sum_all', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('position_category', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_analytics_daily_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'product_id', name=op.f('pk_analytics_daily'))
    )
    op.create_index('ix_analytics_product_date', 'analytics_daily', ['product_id', 'date'], unique=False)
    op.create_table('markers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ozon_account_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('marker_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('value_before', sa.JSON(), nullable=True),
    sa.Column('value_after', sa.JSON(), nullable=True),
    sa.Column('effect_calculated_at', sa.UUID(), nullable=True),
    sa.Column('effect_summary', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_markers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_markers_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_markers_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_markers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markers'))
    )
    op.create_index(op.f('ix_markers_company_id'), 'markers', ['company_id'], unique=False)
    op.create_index('ix_markers_created', 'markers', ['created_at'], unique=False)
    op.create_index(op.f('ix_markers_ozon_account_id'), 'markers', ['ozon_account_id'], unique=False)
    op.create_index(op.f('ix_markers_product_id'), 'markers', ['product_id'], unique=False)
    op.create_index('ix_markers_type', 'markers', ['marker_type'], unique=False)
    op.create_index(op.f('ix_markers_user_id'), 'markers', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('ozon_sku', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('marketing_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_index', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'product_id', name=op.f('pk_price_history'))
    )
    op.create_index('ix_price_history_product_time', 'price_history', ['product_id', 'time'], unique=False)
    op.create_table('stocks',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_type', sa.String(length=20), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('free_to_sell', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('in_transit', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stocks_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'product_id', 'warehouse_type', name=op.f('pk_stocks'))
    )
    op.create_index('ix_stocks_product_time', 'stocks', ['product_id', 'time'], unique=False)
    op.create_index('ix_stocks_warehouse', 'stocks', ['warehouse_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocks_warehouse', table_name='stocks')
    op.drop_index('ix_stocks_product_time', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_price_history_product_time', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_markers_user_id'), table_name='markers')
    op.drop_index('ix_markers_type', table_name='markers')
    op.drop_index(op.f('ix_markers_product_id'), table_name='markers')
    op.drop_index(op.f('ix_markers_ozon_account_id'), table_name='markers')
    op.drop_index('ix_markers_created', table_name='markers')
    op.drop_index(op.f('ix_markers_company_id'), table_name='markers')
    op.drop_table('markers')
    op.drop_index('ix_analytics_product_date', table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_index('ix_transactions_type', table_name='transactions')
    op.drop_index('ix_transactions_account_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_sync_logs_ozon_account_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_products_ozon_account_id'), table_name='products')
    op.drop_index('ix_products_offer_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_ozon_account_id'), table_name='orders')
    op.drop_index('ix_orders_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ozon_accounts_company_id'), table_name='ozon_accounts')
    op.drop_table('ozon_accounts')
    op.drop_table('roles')
    op.drop_table('companies')
    # ### end Alembic commands ###
