"""phase 2 full schema

Revision ID: 2540a3b19862
Revises: 0001_premium_perf_ad
Create Date: 2026-05-28 10:57:03.775493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2540a3b19862'
down_revision: Union[str, None] = '0001_premium_perf_ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_competitors',
    sa.Column('ozon_seller_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_competitors')),
    sa.UniqueConstraint('ozon_seller_id', name=op.f('uq_market_competitors_ozon_seller_id'))
    )
    op.create_index('ix_market_competitors_seller', 'market_competitors', ['ozon_seller_id'], unique=False)
    op.create_table('market_cross_platform',
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_cross_platform'))
    )
    op.create_index('ix_market_cross_competitor_platform', 'market_cross_platform', ['competitor_name', 'platform'], unique=False)
    op.create_table('market_search_queries',
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_search_queries'))
    )
    op.create_index('ix_market_search_queries_period', 'market_search_queries', ['period'], unique=False)
    op.create_index('ix_market_search_queries_query', 'market_search_queries', ['query'], unique=False)
    op.create_table('market_trends_daily',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('demand_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('growth_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('new_products_count', sa.Integer(), nullable=True),
    sa.Column('seasonal_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('time', 'category', name=op.f('pk_market_trends_daily'))
    )
    op.create_index('ix_market_trends_category_time', 'market_trends_daily', ['category', 'time'], unique=False)
    op.create_table('market_competitor_prices',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('ozon_sku', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stock_present', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('search_position', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['market_competitors.id'], name=op.f('fk_market_competitor_prices_competitor_id_market_competitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'competitor_id', 'ozon_sku', name=op.f('pk_market_competitor_prices'))
    )
    op.create_index('ix_market_competitor_prices_competitor_time', 'market_competitor_prices', ['competitor_id', 'time'], unique=False)
    op.create_index('ix_market_competitor_prices_sku', 'market_competitor_prices', ['ozon_sku'], unique=False)
    op.create_table('account_balance_snapshots',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('available_now', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pending', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('withheld_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('next_payout_date', sa.Date(), nullable=True),
    sa.Column('next_payout_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_account_balance_snapshots_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_balance_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'ozon_account_id', name=op.f('pk_account_balance_snapshots'))
    )
    op.create_index('ix_balance_snapshots_user_time', 'account_balance_snapshots', ['user_id', 'time'], unique=False)
    op.create_table('ai_chats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_chats'))
    )
    op.create_index('ix_ai_chats_user', 'ai_chats', ['user_id'], unique=False)
    op.create_table('ai_usage_monthly',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('tokens_input', sa.BigInteger(), nullable=False),
    sa.Column('tokens_output', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_monthly_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_monthly')),
    sa.UniqueConstraint('user_id', 'period', 'model', name='uq_ai_usage_monthly_triple')
    )
    op.create_index('ix_ai_usage_monthly_user', 'ai_usage_monthly', ['user_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=True),
    sa.Column('marker_type', sa.String(length=40), nullable=False),
    sa.Column('threshold_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quiet_hours_json', sa.JSON(), nullable=True),
    sa.Column('channels_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_alert_rules_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index('ix_alert_rules_user', 'alert_rules', ['user_id'], unique=False)
    op.create_table('alerts_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marker_type', sa.String(length=40), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_alerts_history_ozon_account_id_ozon_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_alerts_history_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts_history'))
    )
    op.create_index('ix_alerts_history_user_triggered', 'alerts_history', ['user_id', 'triggered_at'], unique=False)
    op.create_table('cancellations',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('posting_number', sa.String(length=100), nullable=False),
    sa.Column('ozon_sku', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cancel_reason_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason_text', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiator', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_cancellations_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cancellations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellations'))
    )
    op.create_index('ix_cancellations_account_date', 'cancellations', ['ozon_account_id', 'cancelled_at'], unique=False)
    op.create_index('ix_cancellations_posting', 'cancellations', ['posting_number'], unique=False)
    op.create_index('ix_cancellations_user', 'cancellations', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ozon_chat_id', sa.String(length=100), nullable=False),
    sa.Column('posting_number', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_chats_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index('ix_chats_ozon_chat', 'chats', ['ozon_chat_id'], unique=False)
    op.create_index('ix_chats_user', 'chats', ['user_id'], unique=False)
    op.create_table('company_members',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_members_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_company_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_members')),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_members_company_user')
    )
    op.create_index('ix_company_members_user', 'company_members', ['user_id'], unique=False)
    op.create_table('cost_import_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cost_import_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_import_log'))
    )
    op.create_index('ix_cost_import_log_user', 'cost_import_log', ['user_id'], unique=False)
    op.create_table('email_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_log'))
    )
    op.create_index('ix_email_log_status', 'email_log', ['status'], unique=False)
    op.create_index('ix_email_log_user_created', 'email_log', ['user_id', 'created_at'], unique=False)
    op.create_table('financial_reports',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ozon_report_code', sa.String(length=100), nullable=True),
    sa.Column('total_accrued', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_withheld', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_to_payout', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_file_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_financial_reports_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports'))
    )
    op.create_index('ix_financial_reports_account_period', 'financial_reports', ['ozon_account_id', 'period_from', 'period_to'], unique=False)
    op.create_index('ix_financial_reports_user', 'financial_reports', ['user_id'], unique=False)
    op.create_table('manual_reconciliation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('uploaded_file_url', sa.Text(), nullable=True),
    sa.Column('uploaded_file_type', sa.String(length=40), nullable=True),
    sa.Column('flowoi_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flowoi_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flowoi_logistics', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flowoi_ads', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flowoi_cogs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flowoi_net_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ozon_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ozon_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ozon_logistics', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ozon_payout', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comparison_json', sa.JSON(), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('checked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], name=op.f('fk_manual_reconciliation_checked_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_manual_reconciliation_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manual_reconciliation_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_reconciliation'))
    )
    op.create_index('ix_manual_reconciliation_account_period', 'manual_reconciliation', ['ozon_account_id', 'period_from', 'period_to'], unique=False)
    op.create_index('ix_manual_reconciliation_user', 'manual_reconciliation', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('ozon_financing',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(length=40), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_ozon_financing_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ozon_financing_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ozon_financing'))
    )
    op.create_index('ix_ozon_financing_user', 'ozon_financing', ['user_id'], unique=False)
    op.create_table('reconciliation',
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('realtime_sum', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('report_sum', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance_sum', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delta_rt_report', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delta_report_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_reconciliation_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reconciliation_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation'))
    )
    op.create_index('ix_reconciliation_account_period', 'reconciliation', ['ozon_account_id', 'period_from', 'period_to'], unique=False)
    op.create_index('ix_reconciliation_user', 'reconciliation', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_suppliers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index('ix_suppliers_user', 'suppliers', ['user_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_team_invitations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_team_invitations_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invitations')),
    sa.UniqueConstraint('token', name='uq_team_invitations_token')
    )
    op.create_index('ix_team_invitations_company_email', 'team_invitations', ['company_id', 'email'], unique=False)
    op.create_table('ad_campaign_products',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('bid', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], name=op.f('fk_ad_campaign_products_campaign_id_ad_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_ad_campaign_products_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_campaign_products'))
    )
    op.create_index('ix_ad_campaign_products_campaign', 'ad_campaign_products', ['campaign_id'], unique=False)
    op.create_index('ix_ad_campaign_products_product', 'ad_campaign_products', ['product_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=30), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('context_page', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], name=op.f('fk_ai_messages_chat_id_ai_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index('ix_ai_messages_chat_created', 'ai_messages', ['chat_id', 'created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('ozon_message_id', sa.String(length=100), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_chat', 'chat_messages', ['chat_id'], unique=False)
    op.create_table('manual_reconciliation_lines',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('flowoi_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ozon_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delta', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delta_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['manual_reconciliation.id'], name=op.f('fk_manual_reconciliation_lines_reconciliation_id_manual_reconciliation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_reconciliation_lines'))
    )
    op.create_index('ix_manual_recon_lines_parent', 'manual_reconciliation_lines', ['reconciliation_id'], unique=False)
    op.create_table('member_account_access',
    sa.Column('company_member_id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('can_view', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('can_edit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_member_id'], ['company_members.id'], name=op.f('fk_member_account_access_company_member_id_company_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_member_account_access_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_account_access')),
    sa.UniqueConstraint('company_member_id', 'ozon_account_id', name='uq_member_account_access_pair')
    )
    op.create_table('ozon_financing_movements',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('financing_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('affects_pnl', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('affects_cashflow', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('affects_debt', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['financing_id'], ['ozon_financing.id'], name=op.f('fk_ozon_financing_movements_financing_id_ozon_financing'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'financing_id', 'seq', name=op.f('pk_ozon_financing_movements'))
    )
    op.create_index('ix_financing_movements_fin', 'ozon_financing_movements', ['financing_id'], unique=False)
    op.create_table('product_cost_history',
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_to_wh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('packaging', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_costs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('full_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='RUB', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_product_cost_history_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_product_cost_history_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_cost_history_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_cost_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('effective_from', 'product_id', name=op.f('pk_product_cost_history')),
    sa.UniqueConstraint('id', name='uq_product_cost_history_id')
    )
    op.create_index('ix_product_cost_user', 'product_cost_history', ['user_id'], unique=False)
    op.create_table('product_supply_params',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('lead_time_total_days', sa.Integer(), nullable=False),
    sa.Column('lead_time_production_days', sa.Integer(), nullable=True),
    sa.Column('lead_time_delivery_days', sa.Integer(), nullable=True),
    sa.Column('lead_time_processing_days', sa.Integer(), nullable=True),
    sa.Column('moq', sa.Integer(), server_default='1', nullable=False),
    sa.Column('batch_step', sa.Integer(), server_default='1', nullable=False),
    sa.Column('batch_strict', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('safety_stock_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('is_primary_supplier', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('longterm_window_days', sa.Integer(), server_default='365', nullable=False),
    sa.Column('shortterm_window_days', sa.Integer(), server_default='14', nullable=False),
    sa.Column('forecast_strategy', sa.String(length=20), server_default='balanced', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_supply_params_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_product_supply_params_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_supply_params_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_supply_params')),
    sa.UniqueConstraint('user_id', 'product_id', 'supplier_id', name='uq_supply_params_user_product_supplier')
    )
    op.create_index('ix_supply_params_user_product', 'product_supply_params', ['user_id', 'product_id'], unique=False)
    op.create_table('sales_velocity_cache',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('longterm_window_days', sa.Integer(), nullable=False),
    sa.Column('longterm_avg_daily', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('longterm_seasonal_factor', sa.Numeric(precision=8, scale=4), server_default='1.0', nullable=False),
    sa.Column('longterm_adjusted_daily', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('longterm_confidence', sa.String(length=20), nullable=False),
    sa.Column('shortterm_window_days', sa.Integer(), nullable=False),
    sa.Column('shortterm_avg_daily', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('trend_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trend_signal', sa.String(length=20), nullable=False),
    sa.Column('recommended_daily', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recommendation_basis', sa.Text(), nullable=True),
    sa.Column('total_units_sold', sa.Integer(), nullable=False),
    sa.Column('days_in_stock', sa.Integer(), nullable=False),
    sa.Column('days_out_of_stock', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_sales_velocity_cache_ozon_account_id_ozon_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_velocity_cache_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_velocity_cache_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'product_id', name=op.f('pk_sales_velocity_cache'))
    )
    op.create_index('ix_sales_velocity_signal', 'sales_velocity_cache', ['trend_signal'], unique=False)
    op.create_index('ix_sales_velocity_user_product', 'sales_velocity_cache', ['user_id', 'product_id'], unique=False)
    op.create_table('supplier_orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ozon_account_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='created', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ozon_account_id'], ['ozon_accounts.id'], name=op.f('fk_supplier_orders_ozon_account_id_ozon_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_orders_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_orders_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_supplier_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_orders'))
    )
    op.create_index('ix_supplier_orders_user_product', 'supplier_orders', ['user_id', 'product_id'], unique=False)
    op.add_column('ad_campaigns', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('ad_campaigns', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('ad_campaigns', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('ad_campaigns', sa.Column('created_at_ozon', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ad_campaigns', 'daily_budget',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('ad_campaigns', 'weekly_budget',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('ad_campaigns', 'budget',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('ad_campaigns', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('ix_ad_campaigns_user', 'ad_campaigns', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_ad_campaigns_user_id_users'), 'ad_campaigns', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # product_id входит в PK; для текущих (пустых) и будущих агрегатов
    # без разбивки по товарам подставляем NIL UUID по умолчанию.
    op.add_column(
        'ad_statistics',
        sa.Column(
            'product_id',
            sa.UUID(),
            nullable=False,
            server_default='00000000-0000-0000-0000-000000000000',
        ),
    )
    op.add_column('ad_statistics', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column(
        'ad_statistics',
        sa.Column('impressions', sa.BigInteger(), nullable=False, server_default='0'),
    )
    op.add_column(
        'ad_statistics',
        sa.Column('spend', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.add_column('ad_statistics', sa.Column('roas', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('ad_statistics', sa.Column('avg_bid', sa.Numeric(precision=14, scale=2), nullable=True))
    op.alter_column('ad_statistics', 'revenue',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ad_statistics', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # NOTE: ad_statistics_date_idx — внутренний индекс TimescaleDB-hypertable,
    # дропать его нельзя (alembic autogen его «увидел» и предложил, мы убрали).
    op.create_index('ix_ad_statistics_product', 'ad_statistics', ['product_id'], unique=False)
    op.create_index('ix_ad_statistics_user', 'ad_statistics', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_ad_statistics_user_id_users'), 'ad_statistics', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ad_statistics', 'views')
    op.drop_column('ad_statistics', 'money_spent')
    op.add_column('ozon_accounts', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False))
    # NOTE: price_history_time_idx — внутренний индекс TimescaleDB, не трогаем.
    op.add_column('questions', sa.Column('user_id', sa.UUID(), nullable=True))
    # Существующие строки questions пустые → можно сразу NOT NULL с server_default=''
    op.add_column(
        'questions',
        sa.Column('text', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column('questions', sa.Column('created_at_ozon', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('questions', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_questions_account_date'), table_name='questions')
    op.create_index('ix_questions_account_date', 'questions', ['ozon_account_id', 'created_at_ozon'], unique=False)
    op.create_index('ix_questions_user', 'questions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_questions_user_id_users'), 'questions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'question_date')
    op.drop_column('questions', 'question_text')
    op.add_column('realization_lines', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('realization_lines', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('ix_realization_user', 'realization_lines', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_realization_lines_user_id_users'), 'realization_lines', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('returns', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('returns', sa.Column('order_id', sa.UUID(), nullable=True))
    op.add_column('returns', sa.Column('accepted_from_customer_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('returns', sa.Column('returned_to_seller_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('returns', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('ix_returns_user', 'returns', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_returns_user_id_users'), 'returns', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_returns_order_id_orders'), 'returns', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('created_at_ozon', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'reviews',
        sa.Column('has_answer', sa.Boolean(), nullable=False, server_default='false'),
    )
    op.add_column('reviews', sa.Column('our_answer_text', sa.Text(), nullable=True))
    op.alter_column('reviews', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_reviews_account_date'), table_name='reviews')
    op.create_index('ix_reviews_account_date', 'reviews', ['ozon_account_id', 'created_at_ozon'], unique=False)
    op.create_index('ix_reviews_user', 'reviews', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('reviews', 'review_text')
    op.drop_column('reviews', 'has_response')
    op.drop_column('reviews', 'review_date')
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('operation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('accruals_for_sale', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('sale_commission', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('delivery_to_customer', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('return_logistics', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('last_mile', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('storage', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('placement', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('acquiring', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('advertising', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('utilization', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('fine', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('compensation', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.create_index('ix_transactions_category', 'transactions', ['category'], unique=False)
    op.create_index('ix_transactions_user', 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_transactions_user_id_users'), 'transactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transactions', 'accruals')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))

    # Rename audit_logs.meta → metadata_json (consistent с user spec)
    op.alter_column('audit_logs', 'meta', new_column_name='metadata_json')
    # ### end Alembic commands ###

    # ============================================================
    # TimescaleDB hypertable conversion (autogen этого не умеет)
    # ============================================================
    for table, time_col, interval in (
        ("product_cost_history", "effective_from", "30 days"),
        ("ozon_financing_movements", "time", "30 days"),
        ("account_balance_snapshots", "time", "7 days"),
        ("market_competitor_prices", "time", "7 days"),
        ("market_trends_daily", "time", "30 days"),
        ("sales_velocity_cache", "time", "7 days"),
    ):
        op.execute(
            f"SELECT create_hypertable("
            f"'{table}', '{time_col}', "
            f"chunk_time_interval => INTERVAL '{interval}', "
            f"if_not_exists => TRUE)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.add_column('transactions', sa.Column('accruals', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_transactions_user_id_users'), 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_user', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('transactions', 'compensation')
    op.drop_column('transactions', 'fine')
    op.drop_column('transactions', 'utilization')
    op.drop_column('transactions', 'advertising')
    op.drop_column('transactions', 'acquiring')
    op.drop_column('transactions', 'placement')
    op.drop_column('transactions', 'storage')
    op.drop_column('transactions', 'last_mile')
    op.drop_column('transactions', 'return_logistics')
    op.drop_column('transactions', 'delivery_to_customer')
    op.drop_column('transactions', 'services')
    op.drop_column('transactions', 'sale_commission')
    op.drop_column('transactions', 'accruals_for_sale')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'operation_date')
    op.drop_column('transactions', 'user_id')
    op.add_column('reviews', sa.Column('review_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('has_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_index('ix_reviews_user', table_name='reviews')
    op.drop_index('ix_reviews_account_date', table_name='reviews')
    op.create_index(op.f('ix_reviews_account_date'), 'reviews', ['ozon_account_id', 'review_date'], unique=False)
    op.alter_column('reviews', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('reviews', 'our_answer_text')
    op.drop_column('reviews', 'has_answer')
    op.drop_column('reviews', 'created_at_ozon')
    op.drop_column('reviews', 'text')
    op.drop_column('reviews', 'user_id')
    op.drop_constraint(op.f('fk_returns_order_id_orders'), 'returns', type_='foreignkey')
    op.drop_constraint(op.f('fk_returns_user_id_users'), 'returns', type_='foreignkey')
    op.drop_index('ix_returns_user', table_name='returns')
    op.alter_column('returns', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('returns', 'returned_to_seller_at')
    op.drop_column('returns', 'accepted_from_customer_at')
    op.drop_column('returns', 'order_id')
    op.drop_column('returns', 'user_id')
    op.drop_constraint(op.f('fk_realization_lines_user_id_users'), 'realization_lines', type_='foreignkey')
    op.drop_index('ix_realization_user', table_name='realization_lines')
    op.alter_column('realization_lines', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('realization_lines', 'user_id')
    op.add_column('questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('question_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_questions_user_id_users'), 'questions', type_='foreignkey')
    op.drop_index('ix_questions_user', table_name='questions')
    op.drop_index('ix_questions_account_date', table_name='questions')
    op.create_index(op.f('ix_questions_account_date'), 'questions', ['ozon_account_id', 'question_date'], unique=False)
    op.alter_column('questions', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('questions', 'created_at_ozon')
    op.drop_column('questions', 'text')
    op.drop_column('questions', 'user_id')
    op.create_index(op.f('price_history_time_idx'), 'price_history', [sa.literal_column('time DESC')], unique=False)
    op.drop_column('ozon_accounts', 'is_system')
    op.add_column('ad_statistics', sa.Column('money_spent', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('ad_statistics', sa.Column('views', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_ad_statistics_user_id_users'), 'ad_statistics', type_='foreignkey')
    op.drop_index('ix_ad_statistics_user', table_name='ad_statistics')
    op.drop_index('ix_ad_statistics_product', table_name='ad_statistics')
    op.create_index(op.f('ad_statistics_date_idx'), 'ad_statistics', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('ad_statistics', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('ad_statistics', 'revenue',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_column('ad_statistics', 'avg_bid')
    op.drop_column('ad_statistics', 'roas')
    op.drop_column('ad_statistics', 'spend')
    op.drop_column('ad_statistics', 'impressions')
    op.drop_column('ad_statistics', 'user_id')
    op.drop_column('ad_statistics', 'product_id')
    op.drop_constraint(op.f('fk_ad_campaigns_user_id_users'), 'ad_campaigns', type_='foreignkey')
    op.drop_index('ix_ad_campaigns_user', table_name='ad_campaigns')
    op.alter_column('ad_campaigns', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('ad_campaigns', 'budget',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('ad_campaigns', 'weekly_budget',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('ad_campaigns', 'daily_budget',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.drop_column('ad_campaigns', 'created_at_ozon')
    op.drop_column('ad_campaigns', 'end_date')
    op.drop_column('ad_campaigns', 'start_date')
    op.drop_column('ad_campaigns', 'user_id')
    op.drop_index('ix_supplier_orders_user_product', table_name='supplier_orders')
    op.drop_table('supplier_orders')
    op.drop_index('ix_sales_velocity_user_product', table_name='sales_velocity_cache')
    op.drop_index('ix_sales_velocity_signal', table_name='sales_velocity_cache')
    op.drop_table('sales_velocity_cache')
    op.drop_index('ix_supply_params_user_product', table_name='product_supply_params')
    op.drop_table('product_supply_params')
    op.drop_index('ix_product_cost_user', table_name='product_cost_history')
    op.drop_table('product_cost_history')
    op.drop_index('ix_financing_movements_fin', table_name='ozon_financing_movements')
    op.drop_table('ozon_financing_movements')
    op.drop_table('member_account_access')
    op.drop_index('ix_manual_recon_lines_parent', table_name='manual_reconciliation_lines')
    op.drop_table('manual_reconciliation_lines')
    op.drop_index('ix_chat_messages_chat', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_ai_messages_chat_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_ad_campaign_products_product', table_name='ad_campaign_products')
    op.drop_index('ix_ad_campaign_products_campaign', table_name='ad_campaign_products')
    op.drop_table('ad_campaign_products')
    op.drop_index('ix_team_invitations_company_email', table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index('ix_suppliers_user', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_reconciliation_user', table_name='reconciliation')
    op.drop_index('ix_reconciliation_account_period', table_name='reconciliation')
    op.drop_table('reconciliation')
    op.drop_index('ix_ozon_financing_user', table_name='ozon_financing')
    op.drop_table('ozon_financing')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_manual_reconciliation_user', table_name='manual_reconciliation')
    op.drop_index('ix_manual_reconciliation_account_period', table_name='manual_reconciliation')
    op.drop_table('manual_reconciliation')
    op.drop_index('ix_financial_reports_user', table_name='financial_reports')
    op.drop_index('ix_financial_reports_account_period', table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index('ix_email_log_user_created', table_name='email_log')
    op.drop_index('ix_email_log_status', table_name='email_log')
    op.drop_table('email_log')
    op.drop_index('ix_cost_import_log_user', table_name='cost_import_log')
    op.drop_table('cost_import_log')
    op.drop_index('ix_company_members_user', table_name='company_members')
    op.drop_table('company_members')
    op.drop_index('ix_chats_user', table_name='chats')
    op.drop_index('ix_chats_ozon_chat', table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_cancellations_user', table_name='cancellations')
    op.drop_index('ix_cancellations_posting', table_name='cancellations')
    op.drop_index('ix_cancellations_account_date', table_name='cancellations')
    op.drop_table('cancellations')
    op.drop_index('ix_alerts_history_user_triggered', table_name='alerts_history')
    op.drop_table('alerts_history')
    op.drop_index('ix_alert_rules_user', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_ai_usage_monthly_user', table_name='ai_usage_monthly')
    op.drop_table('ai_usage_monthly')
    op.drop_index('ix_ai_chats_user', table_name='ai_chats')
    op.drop_table('ai_chats')
    op.drop_index('ix_balance_snapshots_user_time', table_name='account_balance_snapshots')
    op.drop_table('account_balance_snapshots')
    op.drop_index('ix_market_competitor_prices_sku', table_name='market_competitor_prices')
    op.drop_index('ix_market_competitor_prices_competitor_time', table_name='market_competitor_prices')
    op.drop_table('market_competitor_prices')
    op.drop_index('ix_market_trends_category_time', table_name='market_trends_daily')
    op.drop_table('market_trends_daily')
    op.drop_index('ix_market_search_queries_query', table_name='market_search_queries')
    op.drop_index('ix_market_search_queries_period', table_name='market_search_queries')
    op.drop_table('market_search_queries')
    op.drop_index('ix_market_cross_competitor_platform', table_name='market_cross_platform')
    op.drop_table('market_cross_platform')
    op.drop_index('ix_market_competitors_seller', table_name='market_competitors')
    op.drop_table('market_competitors')
    # ### end Alembic commands ###
